#!/usr/bin/env bash
# my comment
splays information about subdomains
# Usage: ./0-world_wide_web domain [subdomain]
# shellcheck disable=SC2086

# Function to query and print subdomain info
check_subdomain() {
    local domain=$1
    local subdomain=$2

    info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4, $5}')
    record_type=$(echo $info | awk '{print $1}')
    destination=$(echo $info | awk '{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        check_subdomain "$domain" "$sub"
    done
else
    check_subdomain "$domain" "$subdomain"
fi

